[project]
name = "pynary"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "construct>=2.10.70",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
